# Generated by Django 5.2.1 on 2025-05-20 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='situacao',
            new_name='situacaoPedido',
        ),
    ]
