# Generated by Django 5.2.1 on 2025-05-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_situacao_pedido_situacaopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacao',
            name='parentesco',
        ),
        migrations.AlterField(
            model_name='relacao',
            name='tipo',
            field=models.CharField(choices=[('ia', 'Indicação amigos'), ('if', 'Indicação familia'), ('rs', 'Redes Sociais')], max_length=250),
        ),
    ]
